-- Cambiar al esquema eshop_api
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = eshop_api;

-- =========================
-- Secuencias
-- =========================
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE PERSONA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE USUARIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE ORIGEN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE SESION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEGUNDO_FA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

-- =========================
-- Tablas
-- =========================
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE PERSONA (
       ID_PERSONA NUMBER(10) DEFAULT PERSONA_SEQ.NEXTVAL PRIMARY KEY,
       NOMBRE VARCHAR2(100) NOT NULL,
       APELLIDOS VARCHAR2(200) NOT NULL,
       CORREO VARCHAR2(150) UNIQUE NOT NULL,
       CELULAR VARCHAR2(20) NOT NULL,
       FECHA_CREACION DATE DEFAULT SYSDATE,
       FECHA_ACTUALIZACION DATE
   )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE USUARIO (
       ID_USUARIO NUMBER(10) DEFAULT USUARIO_SEQ.NEXTVAL PRIMARY KEY,
       NOMBRE VARCHAR2(100) UNIQUE NOT NULL,
       CONTRASENIA VARCHAR2(200) NOT NULL,
       ID_PERSONA NUMBER(10) NOT NULL,
       ID_ORIGEN NUMBER(2) NOT NULL,
       ACTIVO NUMBER(1) NOT NULL,
       BLOQUEO NUMBER(1) NOT NULL,
       FECHA_CREACION DATE DEFAULT SYSDATE,
       FECHA_BLOQUEO DATE,
       FECHA_ACTUALIZACION DATE
   )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE ORIGEN (
       ID_ORIGEN NUMBER(2) DEFAULT ORIGEN_SEQ.NEXTVAL PRIMARY KEY,
       NOMBRE VARCHAR2(100) UNIQUE NOT NULL,
       CLAVE VARCHAR2(10) NOT NULL,
       ESTATUS NUMBER(1) NOT NULL,
       FECHA_CREACION DATE DEFAULT SYSDATE,
       FECHA_ACTUALIZACION DATE
   )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE SESION (
       ID_SESION NUMBER(10) DEFAULT SESION_SEQ.NEXTVAL PRIMARY KEY,
       ID_USUARIO NUMBER(10) NOT NULL,
       JTI VARCHAR2(200) UNIQUE NOT NULL,
       ACTIVO NUMBER(1) NOT NULL,
       FECHA_CREACION DATE DEFAULT SYSDATE,
       FECHA_EXPIRACION DATE NOT NULL,
       FECHA_ACTUALIZACION DATE
   )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE SEGUNDO_FA (
       ID_SEGUNDO_FA NUMBER(10) DEFAULT SEGUNDO_FA_SEQ.NEXTVAL PRIMARY KEY,
       ID_USUARIO NUMBER(10) NOT NULL,
       SECRETO VARCHAR2(64) NOT NULL,
       ACTIVO NUMBER(1) NOT NULL,
       FECHA_CREACION DATE DEFAULT SYSDATE,
       FECHA_ACTUALIZACION DATE
   )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; END;
/

-- =========================
-- Datos iniciales
-- =========================
DECLARE
   v_count NUMBER;
BEGIN
   SELECT COUNT(*) INTO v_count FROM ORIGEN WHERE CLAVE = 'App';
   IF v_count = 0 THEN
      INSERT INTO ORIGEN(NOMBRE, CLAVE, ESTATUS) VALUES ('App Movil', 'App', 1);
      COMMIT;
   END IF;
END;
/