services:
  oracle-xe:
    image: gvenzl/oracle-xe:21.3.0
    container_name: eshop-oracle-xe
    ports:
      - "1521:1521" 
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: MiPasswordSeguro
    volumes:
      - oracle-xe-vol:/opt/oracle/oradata
      - ./01_create_user.sql:/docker-entrypoint-initdb.d/01_create_user.sql
      - ./02_create_schema.sql:/docker-entrypoint-initdb.d/02_create_schema.sql
    restart: always
    networks:
      - eshop-net

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo \"SELECT 1 FROM dual;\" | sqlplus -s system/$${ORACLE_PASSWORD}@localhost/XEPDB1 || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 5m

  eshop-api:
    image: mgalicianegrete/eshop-api:latest
    environment:
      - ConnectionStrings__EShop=${DB_CONNECTION_ESHOP}
    ports:
      - "5000:8080"
    depends_on:
      - oracle-xe
    networks:
      - eshop-net
  eshop-worker:
    image: mgalicianegrete/eshop-worker:latest
    environment:
      - ConnectionStrings__EShop=${DB_CONNECTION_ESHOP}
    depends_on:
      oracle-xe:
        condition: service_healthy

    networks:
      - eshop-net
  eshop-app:
    image: mgalicianegrete/eshop-app:latest
    environment:
      - LOGIN=http://localhost:8080/api/v1/eshop/Login
      - PERSONA_REGISTRO=http://localhost:8080/api/v1/eshop/Persona
      - USUARIO_REGISTRAR=http://localhost:8080/api/v1/eshop/Usuario
      - USUARIO_SEGUNDOFA_GENERAR=http://localhost:8080/api/v1/eshop/Usuario/segundofa
      - USUARIO_SEGUNDOFA_ACTIVAR=http://localhost:8080/api/v1/eshop/Usuario/segundofa/activar
      - FEATURE_FLAG=true
    ports:
      - "8080:80"
    depends_on:
      - oracle-xe
    networks:
      - eshop-net
volumes:
  oracle-xe-vol:

networks:
  eshop-net:
    driver: bridge
